name: Bash Lint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install ShellCheck
              run: sudo apt-get install -y shellcheck

            - name: Lint setup.sh
              run: shellcheck setup.sh

            - name: Lint OCR4Linux.sh
              run: shellcheck OCR4Linux.sh
